### ISSUE TITLE
Use case: I want to see historical demand  imp: 100 est: 2

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#22]
Imp: 100. Est: 2
No dependency.

**Comment by N-Wouda** [comment]
I'll tackle this one later this week. Should not be too hard to achieve, now that ordering is in place.

**Comment by N-Wouda** [comment]
@lukko This seems to align nicely with #29 - would you care to take this one on?

**Comment by lukko** [comment]
Yes, will take care of this.

**Comment by lukko** [comment]
What do you think of this.
Mainly the sidebar on the right. 
Make it so that we can swap the content of it, based on what the user wants to know more about.
It is only layout for now.
<img width="1280" alt="schermafbeelding 2016-11-17 om 20 10 00" src="https://cloud.githubusercontent.com/assets/7871887/20403649/f0eae638-ad01-11e6-902c-3e5a1950eb01.png">
<img width="1280" alt="schermafbeelding 2016-11-17 om 20 09 13" src="https://cloud.githubusercontent.com/assets/7871887/20403650/f10a2750-ad01-11e6-9370-d18743439062.png">

**Comment by N-Wouda** [comment]
This is a great idea! In terms of what happens where though, maybe have the journal (/history) be a button of sorts, with the content slide out of the right part of the window when clicked? That way we do not 'waste' valuable space on something similar to record keeping. It is absolutely important to have, but should IMHO not be shown when not specifically asked for.
