### ISSUE TITLE
As a developer, I want to investigate how we can make the game look more appealing/beautiful/pretty/attractive to kids (EST 3)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#44]

**Comment by N-Wouda** [comment]
@lisavancasteren purely subjective here, but since Sargis is already on another issue, would you perhaps care to think about this one? It's not so much programming, but much more centered around ideas/design.

**Comment by lisavancasteren** [comment]
Sure. But I do not have any hours assigned for this, so I'll first do my hours for the student-assistantship for Iris Vis, I'll look into this after!

**Comment by lisavancasteren** [comment]
Sure. But I do not have any hours assigned for this, so I'll first do my hours for the student-assistantship for Iris Vis, I'll look into this after! You can assign me to it

**Comment by lisavancasteren** [comment]
How to make a game more attractive/appealing to kids:
_Relatively little effort: colors and ease of use
More effort: sounds and mostly, feedback_

**Sounds:** 
Soundtracks, sounds of trucks, etc.
Use sounds for feedback (see ‘feedback’)

**Colors:**
Kids love colors
Make it explicitly clear which elements are interactive with for example colors.
Kids are creative, they would like to design their own trucks/warehouses (maybe the colors)

**Feedback:** 
Give strong and positive feedback
Feedback: adults want feedback when something goes wrong, kids whenever anything happens (right and wrong). Implement feedback in the form of pages changing, items moving or sounds (!). 
Feedback: do not just show ‘this is wrong’, but how they can improve or the right solution. 
Build options like ‘try again’ or ‘try easier’ (that puts you back on an easier level), to encourage another try.
Make failures fun. Like Angry Birds: it is fun to see the bird squawk across the screen. 

**Simplicity/ease of use:** 
Simple storyline 
Simple words (not ‘supply chain’ etc, but words like ‘trucks’) and the fewer words, the better. Better to explain something with a visual demonstration (picture/animation) than with a few sentences. 
If the kid needs to choose multiple numbers/objects, do it in steps, not present it all together on the screen. (choice  1 on a screen, after choice has been made: choice 2 appears on a new screen)
Dragging objects instead of typing numbers

If using an account: be able to add a picture, save progress to make it personal. 

References:
http://preloaded.com/questions-answered-design-games-kids-want/ 
https://www.smashingmagazine.com/2016/01/designing-apps-for-kids-is-not-childs-play/ (!)

**Comment by lisavancasteren** [comment]
## How to make a game more attractive/appealing to kids:
_Relatively little effort: colors and ease of use
More effort: sounds and mostly, feedback_

**Sounds:**
- Soundtracks, sounds of trucks, etc.
- Use sounds for feedback (see ‘feedback’)

**Colors:**
- Kids love colors
- Make it explicitly clear which elements are interactive with for example colors.
- Kids are creative, they would like to design their own trucks/warehouses (maybe the colors)

**Feedback:**
- Give strong and positive feedback
- Feedback: adults want feedback when something goes wrong, kids whenever anything happens (right and wrong). Implement feedback in the form of pages changing, items moving or sounds (!).
- Feedback: do not just show ‘this is wrong’, but how they can improve or the right solution.
- Build options like ‘try again’ or ‘try easier’ (that puts you back on an easier level), to encourage another try.
- Make failures fun. Like Angry Birds: it is fun to see the bird squawk across the screen.

**Simplicity/ease of use:**
- Simple storyline
- Simple words (not ‘supply chain’ etc, but words like ‘trucks’) and the fewer words, the better. Better to explain something with a visual demonstration (picture/animation) than with a few sentences.
- If the kid needs to choose multiple numbers/objects, do it in steps, not present it all together on the screen. (choice 1 on a screen, after choice has been made: choice 2 appears on a new screen)
- Dragging objects instead of typing numbers

- If using an account: be able to add a picture, save progress to make it personal.

References:
http://preloaded.com/questions-answered-design-games-kids-want/
https://www.smashingmagazine.com/2016/01/designing-apps-for-kids-is-not-childs-play/ (!)

**Comment by N-Wouda** [comment]
Closing this for now (issue was solved). We'll use your findings in #54; thank you @lisavancasteren!
